Pandas is used for data manipulation and analysis/cleaning. IT provdes 2 data structures : Series(1d array), data frame is (2d array)

In [ ]:
import pandas as pd

# Create a Series- 1d array. Index is automatically assigned as 0,1,2,3,4
data = [10, 20, 30, 40, 50]
series = pd.Series(data)
print(series)
print(type(series))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.Series'>

In [ ]:
# create series from dictionary . Keys becoem the index and values become the data
data_dict = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
series = pd.Series(data_dict)
print(series)
print(type(series))

a    10
b    20
c    30
d    40
e    50
dtype: int64
<class 'pandas.Series'>

In [ ]:
#creating series with custom index without using dictionary
data = [1, 2, 3, 4, 5,6,7,8,9,10]
index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
series = pd.Series(data, index=index)
print(series)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

In [8]:
# Data frame- multiple columns and rows
# create a data frame from dictionary of list
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}
df = pd.DataFrame(data_dict)
print(df)
print(type(df))

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eve   45      Phoenix
<class 'pandas.DataFrame'>

In [9]:
# Create dataframe from list of dictionaries
data_list = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},  # list of dictionaries
    {'Name': 'Bob', 'Age': 30, 'City': 'Los Angeles'},
    {'Name': 'Charlie', 'Age': 35, 'City': 'Chicago'},
    {'Name': 'David', 'Age': 40, 'City': 'Houston'},
    {'Name': 'Eve', 'Age': 45, 'City': 'Phoenix'}
]
df = pd.DataFrame(data_list)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eve   45      Phoenix

df = pd.read_csv('Online_data.csv')
print(df.head(5))  # print the first 5 rows of the data frame
print(df.tail(5))  # print the last 5 rows of the data frame

In [23]:
# Accessing data from dataframe
data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

In [24]:
df = pd.DataFrame(data_dict)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eve   45      Phoenix

In [25]:
df['Name']  # Accessing a single column
print(df['Name'])
type(df['Name'])  # This will be a Series- we are picking one single column from data frame so it is a series
print(type(df['Name']))

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: str
<class 'pandas.Series'>

In [26]:
df.loc[0]  # Accessing a single row using loc- label based indexing
print(df.loc[0])

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [ ]:
# accessing using index location
df.iloc[1, 2]

'Los Angeles'

In [ ]:
# Accessing a specified element
df.at[0, 'City'] # index with key

'New York'

In [37]:
# Accessing a specified element with iat
df.iat[0, 0] # index with position

'Alice'

In [43]:
# Data manipulation with data frames, addign a column
df['salary']= [50000, 60000, 70000, 80000, 90000]
print(df)

      Name  Age         City  salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
4      Eve   45      Phoenix   90000

In [44]:
# remove a column
df.drop('salary', axis = 1, inplace = True)  # axis = 1 means we want to drop a column, axis = 0 means we want to drop a row
#inplace is to make it permanenet
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eve   45      Phoenix

In [45]:
df.drop(0, inplace = True)
df

      Name  Age         City
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eve   45      Phoenix