In [2]:
import pandas as pd

In [14]:
df=pd.read_csv('data.csv')
print(df.head(5))

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [15]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [16]:
df.describe() #only works with numerical data

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [17]:
df.dtypes #type of data in each column

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

In [18]:
# handlign missing values
df.isnull() #returns a boolean dataframe where True indicates a missing value

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [19]:
df.isnull().any(axis=0)

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [20]:
df.isnull().sum() #count of missing values in each column

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [23]:
df_filled = df.fillna(0, inplace=True) #fill missing values with 0
df_filled

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [24]:
df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean()) #create a new column with filled values
df

          Date Category  Value   Product  Sales Region  Sales_fillNA
0   2023-01-01        A   28.0  Product1  754.0   East         754.0
1   2023-01-02        B   39.0  Product3  110.0  North         110.0
2   2023-01-03        C   32.0  Product2  398.0   East         398.0
3   2023-01-04        B    8.0  Product1  522.0   East         522.0
4   2023-01-05        B   26.0  Product3  869.0  North         869.0
5   2023-01-06        B   54.0  Product3  192.0   West         192.0
6   2023-01-07        A   16.0  Product1  936.0   East         936.0
7   2023-01-08        C   89.0  Product1  488.0   West         488.0
8   2023-01-09        C   37.0  Product3  772.0   West         772.0
9   2023-01-10        A   22.0  Product2  834.0   West         834.0
10  2023-01-11        B    7.0  Product1  842.0  North         842.0
11  2023-01-12        B   60.0  Product2    0.0   West           0.0
12  2023-01-13        A   70.0  Product3  628.0  South         628.0
13  2023-01-14        A   69.0  Product1  423.0   East         423.0
14  2023-01-15        A   47.0  Product2  893.0   West         893.0
15  2023-01-16        C    0.0  Product1  895.0  North         895.0
16  2023-01-17        C   93.0  Product2  511.0  South         511.0
17  2023-01-18        C    0.0  Product1  108.0   West         108.0
18  2023-01-19        A   31.0  Product2  578.0   West         578.0
19  2023-01-20        A   59.0  Product1  736.0   East         736.0
20  2023-01-21        C   82.0  Product3  606.0  South         606.0
21  2023-01-22        C   37.0  Product2  992.0  South         992.0
22  2023-01-23        B   62.0  Product3  942.0  North         942.0
23  2023-01-24        C   92.0  Product2  342.0   West         342.0
24  2023-01-25        A   24.0  Product2  458.0   East         458.0
25  2023-01-26        C   95.0  Product1  584.0   West         584.0
26  2023-01-27        C   71.0  Product2  619.0  North         619.0
27  2023-01-28        C   56.0  Product2  224.0  North         224.0
28  2023-01-29        B    0.0  Product3  617.0  North         617.0
29  2023-01-30        C   51.0  Product2  737.0  South         737.0
30  2023-01-31        B   50.0  Product3  735.0   West         735.0
31  2023-02-01        A   17.0  Product2  189.0   West         189.0
32  2023-02-02        B   63.0  Product3  338.0  South         338.0
33  2023-02-03        C   27.0  Product3    0.0   East           0.0
34  2023-02-04        C   70.0  Product3  669.0   West         669.0
35  2023-02-05        B   60.0  Product2    0.0   West           0.0
36  2023-02-06        C   36.0  Product3  177.0   East         177.0
37  2023-02-07        C    2.0  Product1    0.0  North           0.0
38  2023-02-08        C   94.0  Product1  408.0  South         408.0
39  2023-02-09        A   62.0  Product1  155.0   West         155.0
40  2023-02-10        B   15.0  Product1  578.0   East         578.0
41  2023-02-11        C   97.0  Product1  256.0   East         256.0
42  2023-02-12        A   93.0  Product3  164.0   West         164.0
43  2023-02-13        A   43.0  Product3  949.0   East         949.0
44  2023-02-14        A   96.0  Product3  830.0   East         830.0
45  2023-02-15        B   99.0  Product2  599.0   West         599.0
46  2023-02-16        B    6.0  Product1  938.0  South         938.0
47  2023-02-17        B   69.0  Product3  143.0   West         143.0
48  2023-02-18        C   65.0  Product3  182.0  North         182.0
49  2023-02-19        C   11.0  Product3  708.0  North         708.0

In [ ]:
# Data aggregating and grouping
grouped_mean = df.groupby('Product')['Value'].mean() 
print(grouped_mean)

Product
Product1    40.437500
Product2    52.800000
Product3    52.263158
Name: Value, dtype: float64

In [27]:
df.groupby(['Product', 'Region'])['Value'].sum()

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [30]:
#Merging and joinign dataframes
# Create sample dataframes
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'ID': [2, 3, 4], 'Age': [25, 30, 35]})
df1

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

In [31]:
df2

   ID  Age
0   2   25
1   3   30
2   4   35

In [32]:
pd.merge(df1, df2, on='ID', how='inner') #inner join on ID column

   ID     Name  Age
0   2      Bob   25
1   3  Charlie   30

In [33]:
pd.merge(df1, df2, on='ID', how='outer') #outer join on ID column

   ID     Name   Age
0   1    Alice   NaN
1   2      Bob  25.0
2   3  Charlie  30.0
3   4      NaN  35.0